### ISSUE TITLE
Thank you for this build!!

### ISSUE THREAD

**Issue by shogowarrior** [Darkwulf183/Marlin-2.0.x-Bugfix-LVGL-Ui-pre-defined-update.cbd-and-assets#3]
I am finally able to flash my X5SA with V6 TMC non Titan with marlin and get the screen working! I tried all approaches with nothing but failure :D. 
<img width="417" alt="Screen Shot 2021-09-21 at 12 05 27 PM" src="https://user-images.githubusercontent.com/13209349/134232284-67e75d12-776e-4b74-9e52-5abf98414b51.png">

wohoo!!

I had a quick question on this :). Now that it's flashed with the. custom marlin build? Is it possible to update with custom builds/releases with `update.cbd` in the sd.card? I am a total noob in this thing :D
)

**Comment by Darkwulf183** [comment]
Hi

I don't know, I haven't had a board that needed to be flashed other than via sd card. Since with me also the board in 4-6 weeks flies out just like Marlin then finally from my printers is removed I will invest there also no longer too much time to test and research to operate.

**Comment by shogowarrior** [comment]
Agreed a lot of research and hair pulling! Thank you. I am also looking into the esp3d to use esp01 as Wi-Fi module. This might help making the printer Internet ready 😊.

**Comment by Darkwulf183** [comment]
I only go with Klipper because I save myself the whole thing. The pi does it faster and better than Marlin ever could with the printer board.

**Comment by shogowarrior** [comment]
Got it. I wanted to use klipper but someone said to start with marlin as a newbie. What would you suggest? I only have a pi zero so was wondering klipper in docker in my workstation.

**Comment by Darkwulf183** [comment]
You need Klipper with e.g. mainsail and moonraker on a system which you can connect directly to the board via usb on the original board. With the accessory boards via usb uart or Canbus. Since the board does nothing more with Klipper except to take over the commands from the pi will work with the dokker quite badly. Read you best first in the topic. And come to my YouTube channel. There will soon come all the conversions for the tronxy when the custom anet is finished which I am building with its own frame designed by me. Then it goes off with the big tronxy conversion to skr board and Klipper. YT Channel: Darkwulf1986

**Comment by shogowarrior** [comment]
Makes sense! I did start following your YouTube and ended up here 😁   Looking forward to learning from you :). Please do TronXY + Klipper soon!

**Comment by Darkwulf183** [comment]
Tronxy  change to Klipper is Planned for Nov or Dec 2021.
